name: Reusable workflow

on:
  workflow_call:
    inputs:
      who-to-greet:
        description: 'The person to greet'
        type: string
        required: true
        default: World
    outputs:
      workflow_current_time:
        description: 'The time when greeting.'
        value: ${{ jobs.reusable-job.outputs.current-time }}
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    # time出力パラメータをjobのアウトプットに指定する
    outputs: 
      # time Stepの中の id timeのアウトプットをcurrent-timeとして出力指定
      current-time: ${{ steps.time.outputs.time }}
    steps:
      - name: Greet someone
        run: echo "Hellow ${{ inputs.who-to-greet }}"
      - name: Set time
        id: time
        run: echo "time = $(date)" >> $
        
