name: Reuse other workflow

on: 
  workflow_dispatch:

jobs:
  call_workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: '@HiromichiWakatsuki'

  use-output:
    runs-on: ubuntu-latest
    needs:
      call_workflow
    steps:
      - run: echo "Time was resuable -> ${{ needs.call-workflow.outputs.current-time }}"
